import { buildMcpMarkdownSection } from '../utils/mcp.js';

/**
 * Generate AGENTS.md — the universal standard read by Codex, Cursor,
 * GitHub Copilot, Gemini CLI, and most other agents.
 *
 * This is the single source of truth. All other agent files reference this.
 */
export function generateAgentsMd(guidelines, skills, mcpServers, config = {}) {
  const projectName = config.projectName || 'this project';
  const projectDescription = config.projectDescription || '';
  const sections = [];

  // Header
  sections.push(`# AGENTS.md`);
  sections.push(`> Agent instructions for ${projectName}. Generated by [js-boost](https://github.com/your-org/js-boost) — do not edit manually.`);
  if (projectDescription) sections.push(`\n${projectDescription}`);
  sections.push('');

  // Table of contents hint
  sections.push('---');
  sections.push('');

  // Guidelines — inline all content from .ai/guidelines/
  if (guidelines.length > 0) {
    sections.push('## Guidelines');
    sections.push('');
    sections.push('These guidelines define conventions, patterns, and best practices for this project.');
    sections.push('');

    for (const g of guidelines) {
      // Include the full content of each guideline file
      sections.push(g.content);
      sections.push('');
    }
  }

  // Skills — reference section with name + description
  if (skills.length > 0) {
    sections.push('## Agent Skills');
    sections.push('');
    sections.push('The following skills are available in `.ai/skills/`. Load a skill when the task matches its description.');
    sections.push('');

    for (const skill of skills) {
      sections.push(`### ${skill.name}`);
      if (skill.description) sections.push(`${skill.description}`);
      sections.push(`- **Skill file:** \`.ai/skills/${skill.dir}/SKILL.md\``);
      sections.push('');
    }
  }

  // MCP section
  if (Object.keys(mcpServers).length > 0) {
    sections.push(buildMcpMarkdownSection(mcpServers));
  }

  // Footer
  sections.push('---');
  sections.push('');
  sections.push('*This file is auto-generated by `js-boost`. Run `npx js-boost generate` to regenerate.*');

  return sections.join('\n');
}
