/**
 * Generate .cursor/rules/js-boost.mdc for Cursor.
 *
 * Cursor reads .cursorrules (legacy) or .cursor/rules/*.mdc (v0.43+).
 * We generate the modern .cursor/rules/ format.
 * Each guideline becomes its own rule file for better organization.
 */
export function generateCursorRules(guidelines, skills, config = {}) {
  const sections = [];

  sections.push('---');
  sections.push('description: Project guidelines and conventions');
  sections.push('globs: ["**/*"]');
  sections.push('alwaysApply: true');
  sections.push('---');
  sections.push('');

  // Inline all guidelines
  if (guidelines.length > 0) {
    for (const g of guidelines) {
      sections.push(g.content);
      sections.push('');
    }
  }

  // Skills reference
  if (skills.length > 0) {
    sections.push('## Available Skills');
    sections.push('');
    for (const skill of skills) {
      sections.push(`- **${skill.name}**: \`.ai/skills/${skill.dir}/SKILL.md\``);
      if (skill.description) sections.push(`  ${skill.description}`);
    }
    sections.push('');
  }

  sections.push('---');
  sections.push('*Auto-generated by `js-boost`*');

  return sections.join('\n');
}

/**
 * Also generate legacy .cursorrules for older Cursor versions
 */
export function generateCursorRulesLegacy(guidelines, skills, config = {}) {
  const sections = [];

  sections.push('# Cursor Rules');
  sections.push('# Generated by js-boost — edit .ai/guidelines/ instead');
  sections.push('');

  if (guidelines.length > 0) {
    for (const g of guidelines) {
      // Strip markdown headings for legacy format compatibility
      sections.push(g.content);
      sections.push('');
    }
  }

  if (skills.length > 0) {
    sections.push('## Skills');
    for (const skill of skills) {
      sections.push(`- ${skill.name}: .ai/skills/${skill.dir}/SKILL.md`);
    }
  }

  return sections.join('\n');
}
