/**
 * Generate .junie/guidelines.md for JetBrains Junie.
 *
 * Junie reads .junie/guidelines.md and uses it as persistent context
 * for every task. Skills need to be referenced explicitly since Junie
 * doesn't auto-load them from directories.
 */
export function generateJunieGuidelines(guidelines, skills, config = {}) {
  const projectName = config.projectName || 'this project';
  const sections = [];

  sections.push(`# Junie Guidelines — ${projectName}`);
  sections.push('');
  sections.push('> Generated by [js-boost](https://github.com/your-org/js-boost). Do not edit manually.');
  sections.push('');

  // Inline all guidelines
  if (guidelines.length > 0) {
    for (const g of guidelines) {
      sections.push(g.content);
      sections.push('');
    }
  }

  // Skills reference
  if (skills.length > 0) {
    sections.push('## Available Skills');
    sections.push('');
    sections.push('The following skill files contain detailed patterns. Read the relevant SKILL.md before working on tasks in that domain:');
    sections.push('');
    for (const skill of skills) {
      sections.push(`- **${skill.name}**: \`.ai/skills/${skill.dir}/SKILL.md\``);
      if (skill.description) sections.push(`  ${skill.description}`);
    }
    sections.push('');
  }

  sections.push('---');
  sections.push('*Auto-generated by `js-boost`. Source: `.ai/`*');

  return sections.join('\n');
}
